### ISSUE TITLE
FASE 1:Análisis Exploratorio de Datos(EDA)

### ISSUE THREAD

**Issue by luzmarinahg** [Adalab/proyecto-da-promo-b-modulo-3-team-3#2]

**Comment by nerearial** [comment]
SOCIODEMOGRAFICOS - INFORMACION PERSONAL DEL TRABAJADOR:

--------- VERO --------------------------------
- [x] Age: hay edades escritas en letras comparar con date birth
- [x] Over18: mas de la mitad son menores, revisar nulos y comprobar horas al dia pq los menores pueden trabajar como maximo 6h al dia
- [x] Gender: 0 male y 1 female
----------
- [x] Indexacion employeenumber
- [x] Education: explorar para ver rangos, columna education field other
- [x] MaritalStatus: divorciada y casada mal escrito
- [x] DateBirth: se puede dejar fija para hacer la función y sacar la edad con el año actual
- [x] DistanceFromHome: ver los valores negativos

INFORMACION ECONOMICA PERSONAL DE TRABAJADOR:
- [x] WORKLIFEBALANCE: renombrar y quitar comas
- [x] JobRole: primera en mayus
- [x] Salary: fuera o calcular el total anual con los otros
- [x] RemoteWork: fix
- [x] DailyRate: pasarlo a int o float
- [x] HourlyRate: pasarlo a int o float
- [x] MonthlyIncome: pasarlo a int o float
- [x] EnvironmentSatisfaction: va del 1 al 4 y hay hasta 49
- [x] TOTALWORKINGYEARS: renombrar y quitar las comas
- [x] NUMCOMPANIESWORKED: renombrar como los otros
- [x] OverTime: nulos
- [x] YearsInCurrentRole: quitar comas
- [x] YEARSWITHCURRMANAGER: renombrar
- [x] TRATAR NULOS
- [x] - TRATAR DISTANCIA NEGATIVO
- [x] - QUE HACER CON LA PASTA
- [x] - CREAR EDAD ACTULIZADA
- [x] - ORDENAR COLUMNAS
- [x] - QUE HACER REMOTE WORK
- [x] - ID EMPLEADO
- [x] - EXPLORAR NIVELES DE ESTUDIOS Y OTRAS CATEGORIAS PUESTAS CON NUMERO

----------
CONSENSUADO POR TODO EL EQUIPO: 
- [x] Employeenumber: sin decimales y revisar que sean numeros unicos
- [x] SameAsMonthlyIncome: comparar y eliminar
- [x] RoleDepartament: fuera
- [x] StandardHours: revisar si lo borramos
- [x] Employeecount: revisar si lo eliminamos.
- [x] Age: valorar si nos la cargamos
- [x] Over18: mal los datos, nos la cargamos?

**Comment by nerearial** [comment]
COSAS A PREGUNTAR AL PRODUCT OWNER:

- [x] FASE 1 Qué significa o qué hacemos con RemoteWork: fuera
- [x] FASE 1: salario anual tiene el mismo todo el mundo: fuera
- [x] Cómo orientar y qué debe ponerse en el informe, como hacerlo generalmente
- [x] Education filt hay nulos, mirar de sustituirlos por otros???
- [x] Performing rating: solo hay valores de 3 y 4 de puntuacion
- [x] Employeenumber: hay 431 nulos y 1079 valores unicos. Que hacemos con los nulos si no sabemos quien es??? podemos eliminarlos, sustituir por unknown o ponerles valores unicos
