### ISSUE TITLE
FASE 3:Diseño de base de datos e inserción de los datos (Estructor)

### ISSUE THREAD

**Issue by luzmarinahg** [Adalab/proyecto-da-promo-b-modulo-3-team-3#4]
- [x] **Diseño de la Estructura de la Base de Datos:** Deberás definir la estructura de la base de datos. Esto incluye identificar las tablas necesarias y sus relaciones, así como definir las claves primarias y foráneas.
- [x] **Creación de la Base de Datos:** Deberás crear la base de datos utilizando las herramientas aprendidas en el módulo
- [x] **Inserción de Datos Iniciales:** Deberás insertar los datos de los empleados de la empresa en la base de datos.

**Comment by lopezleyre** [comment]
- [x] Crear la base de datos
- [x] Ver donde quedaría mejor la columna Performance Rating
- [x] Cambiariamos EnviromentSatisfaction, WorkLifeBalance a INT
- [x] Monthly Rate a float???
- [ ]

**Comment by VeronicaVerdugo** [comment]
- [ ] Ir anotando los problemas que surgieron a la hora de hacer la base de datos para las historias de usuario

1. [ ] hemos tenido problemas al unir todas las tablas porque no se ocmpletaban las FK

**Comment by lopezleyre** [comment]
- [x] Mirar la tabla union, no se rellena automáticamente
